---
apiVersion: v1
kind: Namespace
metadata:
  name: hme-pic
---
apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  namespace: hme-pic
spec:
  containers:
  - image: systemdevformations/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP